const express = require('express');
const { createDonation, getDonations, getCenterDonations,getAllDonations } = require('../controllers/donations');
const { verifyToken } = require('../middleware/auth');
const router = express.Router();
const auth=require('../middleware/auth');
router.post('/donations', verifyToken, createDonation);
router.get('/donations/user', verifyToken, getDonations);
router.get('/donations/center/:centerId', verifyToken, getCenterDonations);
router.get('/', verifyToken, getAllDonations);
module.exports = router;
